CoreKamp/Controllers/MessageController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.Concrete.Context;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CoreKamp.Controllers
{
    public class MessageController : Controller
    {
        
        NewMessageManager newMessageManager = new NewMessageManager(new EfNewMessageRepository());
        MsSqlContext msSqlContext = new MsSqlContext();
        public IActionResult InBox()
        {
            var userName = User.Identity.Name;
            var userMail = msSqlContext.Users.Where(x => x.UserName == userName).Select(y => y.Email).FirstOrDefault();
            var writerId = msSqlContext.Writers.Where(x => x.WriterMail == userMail).Select(y => y.WriterId).FirstOrDefault();
            var messageValue = newMessageManager.GetInboxListByWriter(writerId);
            return View(messageValue);
        }

        public IActionResult SendBox()
        {
            var userName = User.Identity.Name;
            var userMail = msSqlContext.Users.Where(x => x.UserName == userName).Select(y => y.Email).FirstOrDefault();
            var writerId = msSqlContext.Writers.Where(x => x.WriterMail == userMail).Select(y => y.WriterId).FirstOrDefault();
            var messageValue = newMessageManager.GetSendboxListByWriter(writerId);
            return View(messageValue);
        }

        public IActionResult MessageDetails(int id)
        {
            var messageValue = newMessageManager.GenericGetById(id);
            return View(messageValue);
        }

        [HttpGet]
        public IActionResult SendMessage()
        {
            return View();
        }

        [HttpPost]
        public IActionResult SendMessage(NewMessage newMessage)
        {
            var userName = User.Identity.Name;
            var userMail = msSqlContext.Users.Where(x => x.UserName == userName).Select(y => y.Email).FirstOrDefault();
            var writerId = msSqlContext.Writers.Where(x => x.WriterMail == userMail).Select(y => y.WriterId).FirstOrDefault();
            newMessage.MessageSenderId = writerId;
            newMessage.MessageReceiverId = 2;
            newMessage.MessageStatus = true;
            newMessage.MessageDate = Convert.ToDateTime(DateTime.Now.ToShortDateString());
            newMessageManager.GenericAdd(newMessage);
            return RedirectToAction("InBox");
        }
    }
}

CoreKamp/Views/Message/InBox.cshtml
@using EntityLayer.Concrete
@model List<NewMessage>
@{
    ViewData["Title"] = "InBox";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}
<h1>Gelen Mesajlar</h1>

<table class="table table-hover">
    <thead>
        <tr>
            <th>#</th>
            <th>Gönderen</th>
            <th>Konu</th>
            <th>Tarih</th>
            <th>Mesajı Görüntüle</th>
        </tr>

    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <th>@item.MessageId</th>
            <td>@item.SenderUser.WriterName</td>
            <td>@item.MessageSubject</td>
            <td>@(((DateTime)item.MessageDate).ToString("dd MMMM yyyy"))</td>
            <td><a href="/Message/MessageDetails/@item.MessageId" class="btn btn-success">Görüntüle</a></td>
        </tr>
        }
    </tbody>
</table>
<a href="/Blog/BlogAdd" class="btn btn-primary">Yeni Mesaj Ekle</a>

CoreKamp/Views/Message/MessageDetails.cshtml
@model EntityLayer.Concrete.NewMessage
@{
    ViewData["Title"] = "MessageDetails";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}

<h1>Mesaj Detay Sayfası</h1>

@Html.HiddenFor(x => x.MessageId)
<br />
@Html.Label("Mesaj Başlığı")
@Html.TextBoxFor(x => x.MessageSubject, new { @class = "form-control", disabled = "disabled" })
<br />
@Html.Label("Mesaj Detayı")
@Html.TextAreaFor(x => x.MessageDetails,10,3, new { @class = "form-control", disabled = "disabled", @id = "summernote"  })
<br />

<button class="btn btn-info">Geri Dön</button>

CoreKamp/Views/Message/SendBox.cshtml
@using EntityLayer.Concrete
@model List<NewMessage>
@{
    ViewData["Title"] = "SendBox";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}

<h1>Giden Mesajlar</h1>

<table class="table table-hover">
    <thead>
        <tr>
            <th>#</th>
            <th>Alıcı</th>
            <th>Konu</th>
            <th>Tarih</th>
            <th>Mesajı Görüntüle</th>
        </tr>

    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <th>@item.MessageId</th>
                <td>@item.ReceiverUser.WriterName</td>
                <td>@item.MessageSubject</td>
                <td>@(((DateTime)item.MessageDate).ToString("dd MMMM yyyy"))</td>
                <td><a href="/Message/MessageDetails/@item.MessageId" class="btn btn-success">Görüntüle</a></td>
            </tr>
        }
    </tbody>
</table>
<a href="/Message/SendMessage" class="btn btn-primary">Yeni Mesaj Gönder</a>

CoreKamp/Views/Message/SendMessage.cshtml
@model EntityLayer.Concrete.NewMessage

@{
    ViewData["Title"] = "SendMessage";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}

<h1>Yeni Mesaj</h1>
<br />
<br />

@using (Html.BeginForm("SendMessage", "Message", FormMethod.Post))
{
    @Html.Label("Alıcı")
    <input type="text" class="form-control" />
    <br />
    @Html.Label("Konu")
    @Html.TextBoxFor(x => x.MessageSubject, new { @class = "form-control" })
    <br />
    @Html.Label("Mesaj İçeriği")
    @Html.TextAreaFor(x => x.MessageDetails, 15, 3, new { @class = "form-control", @id = "summernote" })
    <br />

    <button class="btn btn-success">Gönder</button>
}